---
- name: 'Containers hosts base configuration'
  hosts: 'containers_hosts'
  roles:
    - 'fedora_coreos_setup'
    - 'podman_setup'

- name: 'Common containers'
  hosts: 'containers_hosts'
  roles:
    - 'cloudflare_ddns'
    - 'traefik'
    - 'cockpit'
    - 'sshd_rsync'
    # - 'promtail'
    # - 'node_exporter'
    # - 'systemd_exporter'

- name: 'Cloud containers'
  hosts: 'cloud'
  roles:
    - 'nextcloud'
    - 'collabora_online'
    - 'stirling_pdf'
    - 'immich'
    - 'ttrss'
    - 'freshrss'
    - 'it_tools'

- name: 'Home containers'
  hosts: 'home'
  roles:
    # Backups
    - 'rsync_servers'
    - 'mbsync'
    - 'vdirsyncer'
    - 'borgmatic'
    - 'autorestic'
    # Monitoring
    - 'uptime_kuma'
    - 'healthchecks'
    # - 'grafana'
    # - 'prometheus'
    # - 'loki'
    # - 'syslog_ng'
    # Home automation
    # - 'home_assistant'
    # Media
    - 'plex'
    - 'tautulli'
    - 'navidrome'
    - 'calibre'
    - 'calibre_web'
    - 'komga'
    # - 'transmission'
    - 'qbittorrent'
    - 'sabnzbd'
    - 'autobrr'
    # - 'cross_seed'
    - 'flaresolverr'
    - 'unpackerr'
    - 'profilarr'
    - 'prowlarr'
    - 'radarr'
    - 'sonarr'
    - 'bazarr'
    - 'lidarr'
    - 'mylar'
    - 'seerr'
    - 'maintainerr'
    - 'muxarr'
    - 'uldas'
