---
- name: 'Copy nut configuration'
  ansible.builtin.copy:
    src: 'nut.conf'
    dest: '/etc/ups/nut.conf'
    owner: 'root'
    group: 'nut'
    mode: '0640'
  notify: 'Reload nut-monitor service'

- name: 'Template upsmon configuration'
  ansible.builtin.template:
    src: 'upsmon.conf.j2'
    dest: '/etc/ups/upsmon.conf'
    owner: 'root'
    group: 'nut'
    mode: '0640'
  notify: 'Reload nut-monitor service'

- name: 'Create nut-monitor systemd unit override directory'
  ansible.builtin.file:
    path: '/etc/systemd/system/nut-monitor.service.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Copy nut-monitor systemd unit override'
  ansible.builtin.copy:
    src: 'nut-monitor-service-d-network.conf'
    dest: '/etc/systemd/system/nut-monitor.service.d/network.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Reload systemd daemon'

- name: 'Enable and start nut-monitor'
  ansible.builtin.systemd_service:
    name: 'nut-monitor.service'
    enabled: true
    state: 'started'
